name: Publish to pub.dev

# How to release a new version:
# 1. Bump all pubspec.yaml versions and the changelogs
# 2. Push a new tag (e.g. "git tag v1.2.3 && git push origin v1.2.3")
# 3. The "publish" jobs will automatically publish the package to pub.dev
# 4. The "release" job will automatically create a release draft on GitHub

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v1.2.3'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  publish_darturbation:
    uses: ./.github/workflows/publish_template.yml
    with:
      working-directory: .
  release:
    runs-on: ubuntu-latest
    needs: [publish_darturbation]

    steps:
      - uses: actions/checkout@v3
      - name: Draft release
        id: draft_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}